/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CeniRouteImport } from './routes/ceni'
import { Route as GaleriyaRouteImport } from './routes/galeriya'
import { Route as KontaktiRouteImport } from './routes/kontakti'
import { Route as UslugiRouteImport } from './routes/uslugi'
import { Route as ZaNasRouteImport } from './routes/za-nas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CeniRoute = CeniRouteImport.update({
  id: '/ceni',
  path: '/ceni',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriyaRoute = GaleriyaRouteImport.update({
  id: '/galeriya',
  path: '/galeriya',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktiRoute = KontaktiRouteImport.update({
  id: '/kontakti',
  path: '/kontakti',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiRoute = UslugiRouteImport.update({
  id: '/uslugi',
  path: '/uslugi',
  getParentRoute: () => rootRouteImport,
} as any)
const ZaNasRoute = ZaNasRouteImport.update({
  id: '/za-nas',
  path: '/za-nas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ceni': typeof CeniRoute
  '/galeriya': typeof GaleriyaRoute
  '/kontakti': typeof KontaktiRoute
  '/uslugi': typeof UslugiRoute
  '/za-nas': typeof ZaNasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ceni': typeof CeniRoute
  '/galeriya': typeof GaleriyaRoute
  '/kontakti': typeof KontaktiRoute
  '/uslugi': typeof UslugiRoute
  '/za-nas': typeof ZaNasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ceni': typeof CeniRoute
  '/galeriya': typeof GaleriyaRoute
  '/kontakti': typeof KontaktiRoute
  '/uslugi': typeof UslugiRoute
  '/za-nas': typeof ZaNasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ceni' | '/galeriya' | '/kontakti' | '/uslugi' | '/za-nas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ceni' | '/galeriya' | '/kontakti' | '/uslugi' | '/za-nas'
  id:
    | '__root__'
    | '/'
    | '/ceni'
    | '/galeriya'
    | '/kontakti'
    | '/uslugi'
    | '/za-nas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CeniRoute: typeof CeniRoute
  GaleriyaRoute: typeof GaleriyaRoute
  KontaktiRoute: typeof KontaktiRoute
  UslugiRoute: typeof UslugiRoute
  ZaNasRoute: typeof ZaNasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceni': {
      id: '/ceni'
      path: '/ceni'
      fullPath: '/ceni'
      preLoaderRoute: typeof CeniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeriya': {
      id: '/galeriya'
      path: '/galeriya'
      fullPath: '/galeriya'
      preLoaderRoute: typeof GaleriyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakti': {
      id: '/kontakti'
      path: '/kontakti'
      fullPath: '/kontakti'
      preLoaderRoute: typeof KontaktiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi': {
      id: '/uslugi'
      path: '/uslugi'
      fullPath: '/uslugi'
      preLoaderRoute: typeof UslugiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/za-nas': {
      id: '/za-nas'
      path: '/za-nas'
      fullPath: '/za-nas'
      preLoaderRoute: typeof ZaNasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CeniRoute: CeniRoute,
  GaleriyaRoute: GaleriyaRoute,
  KontaktiRoute: KontaktiRoute,
  UslugiRoute: UslugiRoute,
  ZaNasRoute: ZaNasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
